In [ ]:
import torch
import torch.nn as nn

In [ ]:
#Create tensor
x = torch.tensor([1,2,3])
print(x.device)
print(x.shape)
print(x.dtype)

y = torch.rand((3,4))
print(y)
print(y[0])
print(y[:,1])

cpu
torch.Size([3])
torch.int64
tensor([[0.9776, 0.4870, 0.3302, 0.4690],
        [0.7698, 0.3232, 0.9546, 0.3845],
        [0.7307, 0.2242, 0.9458, 0.7886]])
tensor([0.9776, 0.4870, 0.3302, 0.4690])
tensor([0.4870, 0.3232, 0.2242])


In [ ]:
#Tensor Math
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])

print(a + b)
print(a * b)
print(torch.matmul(a,b))


tensor([[ 6,  8],
        [10, 12]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[19, 22],
        [43, 50]])


In [ ]:
#reshaping tensor
x = torch.tensor([1,2,3,4,5,6,7,8])
print(torch.reshape(x, (2,4)))

print(torch.reshape(x, (4,2)))

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [ ]:
#Simple Linear regression training code
X = torch.ones((2,3))
output = torch.tensor([[5.0], [5.0]])
layer = nn.Linear(in_features=3, out_features=1)
preds = layer(X)
loss = nn.MSELoss()(preds, output)
loss.backward()


print(f"Predictions:\n{preds.detach()}\n")
print(f"Loss value: {loss.item():.4f}\n")
print(f"Weight gradients:\n{layer.weight.grad}")

Predictions:
tensor([[-0.4405],
        [-0.4405]])

Loss value: 29.5992

Weight gradients:
tensor([[-10.8810, -10.8810, -10.8810]])


In [ ]:
x = torch.tensor(3.0, requires_grad=True)
y = (x ** 2) + 2*x + 1
y.backward()
print(x.grad)
x.grad.zero_()
y = (x ** 2) + 2*x + 1
y.backward()
print(x.grad)

tensor(8.)
tensor(8.)


In [ ]:
#training loop
class practiceModule(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear1 = nn.Linear(in_features=3, out_features=5)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(in_features=5, out_features=1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    x = self.linear1(x)
    x = self.relu(x)
    x = self.linear2(x)
    x = self.sigmoid(x)
    return x

x = [[1.0,2.0,3.0],[4.0,5.0,6.0],[7.0,8.0,9.0]]
x = torch.tensor(x, requires_grad=True)
model = practiceModule()
param = model.parameters()
#print(param.weights)
y = model(x)
print(y)
y = model(x).sum() #dummy loss function
y.backward()
print(x.grad)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<ReluBackward0>)
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
#training loop. Trained to predict y= 2x with SGD
torch.manual_seed(42)
linear = nn.Linear(1,1)
x = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
y = torch.tensor([[5.0], [8.0], [11.0], [14.0]])
lossfn = nn.MSELoss()
optmise = torch.optim.SGD(linear.parameters(), lr=0.01)
print(linear.weight)
print(linear.bias)

for epoch in range(150):
  preds = linear(x)
  loss = lossfn(preds, y)
  optmise.zero_grad()
  loss.backward()
  optmise.step()
  if epoch % 10 == 0:
    print(loss.item())

print(linear.weight)
print(linear.bias )
w = torch.tensor(([5.0]))
print(linear(w))


Parameter containing:
tensor([[0.7645]], requires_grad=True)
Parameter containing:
tensor([0.8300], requires_grad=True)
51.925899505615234
1.3640716075897217
0.05471572279930115
0.01970888301730156
0.017738377675414085
0.01668465882539749
0.015712955966591835
0.014798395335674286
0.01393706351518631
0.01312581729143858
0.012361813336610794
0.01164231076836586
0.010964657180011272
0.010326439514756203
0.009725378826260567
Parameter containing:
tensor([[3.0797]], requires_grad=True)
Parameter containing:
tensor([1.7658], requires_grad=True)
tensor([17.1641], grad_fn=<ViewBackward0>)


In [ ]:
#training loop. Trained to predict y= 2x with Adam
torch.manual_seed(42)
linear = nn.Linear(1,1)
x = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
y = torch.tensor([[5.0], [8.0], [11.0], [14.0]])
lossfn = nn.MSELoss()
optmise = torch.optim.Adam(linear.parameters(), lr=0.1)
print(linear.weight)
print(linear.bias)

for epoch in range(150):
  preds = linear(x)
  loss = lossfn(preds, y)
  optmise.zero_grad()
  loss.backward()
  optmise.step()
  if epoch % 10 == 0:
    print(loss.item())

print(linear.weight)
print(linear.bias )
w = torch.tensor(([5.0]))
print(linear(w))


Parameter containing:
tensor([[0.7645]], requires_grad=True)
Parameter containing:
tensor([0.8300], requires_grad=True)
51.925899505615234
13.191317558288574
0.5877943634986877
0.7495453357696533
0.787752628326416
0.1334170401096344
0.10726327449083328
0.09683969616889954
0.05797768384218216
0.05418149381875992
0.044456932693719864
0.037915050983428955
0.03231164067983627
0.027218863368034363
0.02287411317229271
Parameter containing:
tensor([[2.8823]], requires_grad=True)
Parameter containing:
tensor([2.3358], requires_grad=True)
tensor([16.7471], grad_fn=<ViewBackward0>)


In [ ]:
#training loop. Trained to predict y= 2x with AdamW
torch.manual_seed(42)
linear = nn.Linear(1,1)
x = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
y = torch.tensor([[5.0], [8.0], [11.0], [14.0]])
lossfn = nn.MSELoss()
optmise = torch.optim.AdamW(linear.parameters(), lr=0.1, weight_decay=0)
print(linear.weight)
print(linear.bias)

for epoch in range(150):
  preds = linear(x)
  loss = lossfn(preds, y)
  optmise.zero_grad()
  loss.backward()
  optmise.step()
  if epoch % 10 == 0:
    print(loss.item())

print(linear.weight)
print(linear.bias )
w = torch.tensor(([5.0]))
print(linear(w))


Parameter containing:
tensor([[0.7645]], requires_grad=True)
Parameter containing:
tensor([0.8300], requires_grad=True)
51.925899505615234
13.191317558288574
0.5877943634986877
0.7495453357696533
0.787752628326416
0.1334170401096344
0.10726327449083328
0.09683969616889954
0.05797768384218216
0.05418149381875992
0.044456932693719864
0.037915050983428955
0.03231164067983627
0.027218863368034363
0.02287411317229271
Parameter containing:
tensor([[2.8823]], requires_grad=True)
Parameter containing:
tensor([2.3358], requires_grad=True)
tensor([16.7471], grad_fn=<ViewBackward0>)


In [ ]:
#training a MNIST dataset
import torch
import torch.nn as nn
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

train_dataset = datasets.MNIST(root = "./data",
                              train = True,
                              download = True,
                              transform = transforms.ToTensor())
test_dataset = datasets.MNIST(root= "./data",
                             train = False,
                             download = True,
                             transform = transforms.ToTensor())

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=64)


class trainMNIST(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear1 = nn.Linear(784, 256)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(256, 10)

  def forward(self, x):
    x = self.linear1(x)
    x = self.relu(x)
    x = self.linear2(x)
    return x

model = trainMNIST()
lossfn = nn.CrossEntropyLoss()
Optimzer = torch.optim.Adam(model.parameters(), lr=0.001)
#training loop
for epoch in range(10):
  for train, label in train_loader:
    x = train.view(train.size(0), -1)
    pred = model(x)
    loss = lossfn(pred, label)
    Optimzer.zero_grad()
    loss.backward()
    Optimzer.step()
  print(f"epoch: {epoch}  loss: {loss.item()}")

#test loop
correct = 0
total = 0
with torch.no_grad():
  for test, label in test_loader:
    x = test.view(test.size(0), -1)
    output = model(x)
    predictions = torch.argmax(output, dim=1)
    correct += (predictions == label).sum().item()

    total += label.size(0)
print(correct)
print(total)



epoch: 0  loss: 0.15465688705444336
epoch: 1  loss: 0.25428563356399536
epoch: 2  loss: 0.06606161594390869
epoch: 3  loss: 0.01472509652376175
epoch: 4  loss: 0.014074401929974556
epoch: 5  loss: 0.039967577904462814
epoch: 6  loss: 0.003688066266477108
epoch: 7  loss: 0.008977609686553478
epoch: 8  loss: 0.010615705512464046
epoch: 9  loss: 0.0004288242489565164
9795
10000
